package ec;

declare MyEvent
	@role(event) 
	@timestamp(init) 
	@duration(length) 
	init : long 
	length : long
	value : Object 
end

rule "Initialiser"
when
then
	insert( new MyEvent(5, 100, "Value") );
	System.out.println("I'm alive!");
end

rule "print"
salience 5
when
	$e: MyEvent()
then
	System.out.println("- " + $e);
end

rule "Error prone"
no-loop
when
	$e: MyEvent( $i: init, $l: length, $v: value )
then
	modify($e) {
		setLength($i * $l);
// Rule Compilation error : [Rule name='Error prone']
// 		ec/Rule_Error_prone_c091df5edd6c4e359140653f030e9780.java (8:509) : The method setLength(long) is undefined for the type Rule_Error_prone_c091df5edd6c4e359140653f030e9780	
	}
end
	